main.c File Reference
Main file for the project.
#include <stdlib.h>
#include <stdio.h>
#include `prototypes.h`
Functions
int main (void)
Entry point of the program.
void mainMenu ()
Displays the main menu and handles user input.
void sensorsMenu ()
Displays the sensors menu and handles user input for sensor-related actions.
void sensorsVal ()
Displays sensor values based on the system state.
void stateAction ()
Performs actions based on the system state.
char speedControl (Traffic color)
Determine the speed of the vehicle based on the traffic light color.
 Traffic setTraffic ()
Sets the traffic light color.
 State setTemp_AC ()
Sets the room temperature and returns the state of the AC system.
 State setTemp_EC ()
Sets the engine temperature and returns the state of the engine temperature controller.
Variables
 SystemState systemState
System state representing the overall state of the vehicle system.
 SystemState * ptr = & systemState
Detailed Description
Main file for the project.
Author
Mohamed Ismail
 Instructor : Mohamed Tarek
Version
1
Date
30/12/2023
Function Documentation
main()
int main (void)
Entry point of the program.
Calls the main menu function and returns 0 upon completion.
Returns
0 upon successful execution.
Definition at line 36 of file main.c.
References mainMenu().
mainMenu()
void mainMenu ()
Displays the main menu and handles user input.
Display the main menu and handle user input.
The main menu provides options to turn on/off the vehicle engine or quit the system. Upon user input, appropriate actions are taken.
Definition at line 50 of file main.c.
References OFF, ptr, RUNNING, stateAction(), SystemState::userInput, and SystemState::vehicleState.
Referenced by main(), and stateAction().
sensorsMenu()
void sensorsMenu ()
Displays the sensors menu and handles user input for sensor-related actions.
Display the sensors menu and handle user input for sensors.
The sensor menu allows the user to perform various actions related to the vehicle's sensors.
Definition at line 102 of file main.c.
References SystemState::AC_State, SystemState::color, SystemState::EC_State, OFF, ptr, SystemState::sensorsInput, sensorsVal(), setTemp_AC(), setTemp_EC(), setTraffic(), stateAction(), SystemState::userInput, SystemState::vehicleState, and WITH_ENGINE_TEMP_CONTROLLER.
Referenced by stateAction().
sensorsVal()
void sensorsVal ()
Displays sensor values based on the system state.
Display sensor values based on the system state.
The sensor values include the vehicle's engine status, speed, AC status, and room/engine temperatures.
Definition at line 175 of file main.c.
References SystemState::AC_State, SystemState::color, SystemState::EC_State, SystemState::engineTemp, OFF, ptr, SystemState::roomTemp, RUNNING, speedControl(), and SystemState::vehicleState.
Referenced by sensorsMenu().
setTemp_AC()
 State setTemp_AC ()
Sets the room temperature and returns the state of the AC system.
Set the room temperature and return the state of the AC system.
User input is taken to set the room temperature, and the AC system state is determined accordingly.
Returns
AC system state.
Definition at line 344 of file main.c.
References OFF, ptr, SystemState::roomTemp, and RUNNING.
Referenced by sensorsMenu().
setTemp_EC()
 State setTemp_EC ()
Sets the engine temperature and returns the state of the engine temperature controller.
Set the engine temperature and return the state of the engine temperature controller.
User input is taken to set the engine temperature, and the engine temperature controller state is determined accordingly.
Returns
Engine temperature controller state.
Definition at line 373 of file main.c.
References SystemState::engineTemp, OFF, ptr, and RUNNING.
Referenced by sensorsMenu().
setTraffic()
 Traffic setTraffic ()
Sets the traffic light color.
Determine vehicle speed based on the traffic light color.
User input is taken to set the traffic light color.
Returns
Traffic light color.
Definition at line 290 of file main.c.
References GREEN, ORANGE, ptr, RED, and SystemState::userInput.
Referenced by sensorsMenu().
speedControl()
char speedControl (Traffic color)
Determine the speed of the vehicle based on the traffic light color.
Parameters
color
Returns
vehicleSpeed
Definition at line 263 of file main.c.
References GREEN, ORANGE, and RED.
Referenced by sensorsVal().
stateAction()
void stateAction ()
Performs actions based on the system state.
Perform actions based on the system state (e.g., turn on/off the engine).
Actions include displaying messages about the vehicle engine status and navigating to the appropriate menu.
Definition at line 242 of file main.c.
References mainMenu(), OFF, ptr, RUNNING, sensorsMenu(), and SystemState::vehicleState.
Referenced by mainMenu(), and sensorsMenu().
Variable Documentation
ptr
 SystemState* ptr = & systemState
Pointer to the system state structure.
Definition at line 27 of file main.c.
Referenced by mainMenu(), sensorsMenu(), sensorsVal(), setTemp_AC(), setTemp_EC(), setTraffic(), and stateAction().
systemState
 SystemState systemState
Initial value:
= {
    OFF, RED, OFF, 35,
    OFF, 140
}
System state representing the overall state of the vehicle system.
Initial values are set for systemState based on configuration options.
Definition at line 20 of file main.c.