prototypes.h File Reference
Data Structures
struct SystemState
Macros
#define WITH_ENGINE_TEMP_CONTROLLER 1
Typedefs
typedef char(* funPTR) (Traffic)
Enumerations
enum State { OFF,
 RUNNING
 }
enum Traffic { RED,
 ORANGE,
 GREEN
 }
Functions
void mainMenu ()
Display the main menu and handle user input.
void sensorsMenu ()
Display the sensors menu and handle user input for sensors.
void sensorsVal ()
Display sensor values based on the system state.
void stateAction ()
Perform actions based on the system state (e.g., turn on/off the engine).
 Traffic setTraffic ()
Determine vehicle speed based on the traffic light color.
char speedControl (Traffic color)
Determine the speed of the vehicle based on the traffic light color.
 State setTemp_AC ()
Set the room temperature and return the state of the AC system.
 State setTemp_EC ()
Set the engine temperature and return the state of the engine temperature controller.
Macro Definition Documentation
WITH_ENGINE_TEMP_CONTROLLER
#define WITH_ENGINE_TEMP_CONTROLLER 1
Definition at line 4 of file prototypes.h.
Typedef Documentation
funPTR
typedef char(* funPTR) (Traffic)
Definition at line 35 of file prototypes.h.
Enumeration Type Documentation
State
enum State
Enumerator
OFF Component is turned off.
RUNNING Component is running.
Definition at line 7 of file prototypes.h.
Traffic
enum Traffic
Enumerator
RED Red traffic light.
ORANGE Orange traffic light.
GREEN Green traffic light.
Definition at line 12 of file prototypes.h.
Function Documentation
mainMenu()
void mainMenu ()
Display the main menu and handle user input.
Display the main menu and handle user input.
The main menu provides options to turn on/off the vehicle engine or quit the system. Upon user input, appropriate actions are taken.
Definition at line 50 of file main.c.
References OFF, ptr, RUNNING, stateAction(), SystemState::userInput, and SystemState::vehicleState.
Referenced by main(), and stateAction().
sensorsMenu()
void sensorsMenu ()
Display the sensors menu and handle user input for sensors.
Display the sensors menu and handle user input for sensors.
The sensor menu allows the user to perform various actions related to the vehicle's sensors.
Definition at line 102 of file main.c.
References SystemState::AC_State, SystemState::color, SystemState::EC_State, OFF, ptr, SystemState::sensorsInput, sensorsVal(), setTemp_AC(), setTemp_EC(), setTraffic(), stateAction(), SystemState::userInput, SystemState::vehicleState, and WITH_ENGINE_TEMP_CONTROLLER.
Referenced by stateAction().
sensorsVal()
void sensorsVal ()
Display sensor values based on the system state.
Display sensor values based on the system state.
The sensor values include the vehicle's engine status, speed, AC status, and room/engine temperatures.
Definition at line 175 of file main.c.
References SystemState::AC_State, SystemState::color, SystemState::EC_State, SystemState::engineTemp, OFF, ptr, SystemState::roomTemp, RUNNING, speedControl(), and SystemState::vehicleState.
Referenced by sensorsMenu().
setTemp_AC()
 State setTemp_AC ()
Set the room temperature and return the state of the AC system.
Returns
AC system state.
Set the room temperature and return the state of the AC system.
User input is taken to set the room temperature, and the AC system state is determined accordingly.
Returns
AC system state.
Definition at line 344 of file main.c.
References OFF, ptr, SystemState::roomTemp, and RUNNING.
Referenced by sensorsMenu().
setTemp_EC()
 State setTemp_EC ()
Set the engine temperature and return the state of the engine temperature controller.
Returns
Engine temperature controller state.
Set the engine temperature and return the state of the engine temperature controller.
User input is taken to set the engine temperature, and the engine temperature controller state is determined accordingly.
Returns
Engine temperature controller state.
Definition at line 373 of file main.c.
References SystemState::engineTemp, OFF, ptr, and RUNNING.
Referenced by sensorsMenu().
setTraffic()
 Traffic setTraffic ()
Determine vehicle speed based on the traffic light color.
Returns
Traffic light color.
Determine vehicle speed based on the traffic light color.
User input is taken to set the traffic light color.
Returns
Traffic light color.
Definition at line 290 of file main.c.
References GREEN, ORANGE, ptr, RED, and SystemState::userInput.
Referenced by sensorsMenu().
speedControl()
char speedControl (Traffic color)
Determine the speed of the vehicle based on the traffic light color.
Parameters
color
Returns
vehicleSpeed
Definition at line 263 of file main.c.
References GREEN, ORANGE, and RED.
Referenced by sensorsVal().
stateAction()
void stateAction ()
Perform actions based on the system state (e.g., turn on/off the engine).
Perform actions based on the system state (e.g., turn on/off the engine).
Actions include displaying messages about the vehicle engine status and navigating to the appropriate menu.
Definition at line 242 of file main.c.
References mainMenu(), OFF, ptr, RUNNING, sensorsMenu(), and SystemState::vehicleState.
Referenced by mainMenu(), and sensorsMenu().